UKHomeOffice/cop-private-translation-service

docker-compose.yml
kube/deployment.yml
src/config/appConfig.js
src/routes/formDataResolveRouter.js

Add Access-Control-Allow-Origin header to the /api/translation/form/:formName route

Add Access-Control-Allow-Origin header

---

package-lock.json
package.json
src/routes/formDataResolveRouter.js

Use CORS module rather than setting the Access Control Allow Origin header

Use CORS module

---

src/index.js
src/routes/formDataResolveRouter.js

Implement CORS for all routes rather than a specific one

Implement CORS for all routes rather than a specific one

---

src/index.js

Correct the path to the private ui url in the config

Correct the path to the private ui url in the config

---

src/config/appConfig.js

Change reference data url to use the external domain as it's used bythe forms

Change reference data url to use the external domain

---

src/config/appConfig.js
src/models/EnvironmentContext.js
src/services/PlatformDataService.js
test/setUpTests.js

Add an external url for operational data which can be used in the forms

Add an external url for operational data which can be used in the forms

---

src/form/CustomPropertiesVisitor.js
src/form/FormComponentVisitor.js
src/form/SelectComponentVisitor.js
test/form/CustomPropertiesVisitor.test.js

- Moved custom property login from SelectComponentVisitor into new CustomPropertiesVisitor class
- Add unit tests for CustomPropertiesVisitor class

Make custom properties available for all fields

---

src/utilities/handlers/responseHandler.js

Set a default error status code

Set a default error status code

---

src/controllers/FormTranslateController.js
src/form/FormTranslator.js
src/routes/formDataResolveRouter.js
src/utilities/handlers/responseHandler.js

Add logging to give more of an idea of what's happening when approving an onboarded user

Add logging

---

src/routes/formDataResolveRouter.js
src/utilities/handlers/responseHandler.js

Add more logging

---

src/utilities/axios.js

Always log the response from api calls

Always log the response from api calls

---

src/index.js

This will enable us to be able to point a local version of the app to the dev env

Permit multiple cors origins

---

package.json
src/config/winston.js
src/controllers/FormTranslateController.js
src/form/FormTranslator.js
src/index.js
src/models/FormComponent.js
src/models/ShiftDetailsContext.js
src/services/DataContextFactory.js
src/services/FormEngineService.js
src/services/PlatformDataService.js
src/services/ProcessService.js

This fixes all the linting errors

Fix linting

---

.drone.yml
package.json
test/controllers/formDataResolveControllerIframe.test.js
test/controllers/formDataResolveControllerImg.test.js
test/routes/formDataResolveRoutes.test.js
test/routes/healthRoutes.test.js

- Run the linter in drone
- Add tests to the linting
- Add some eslint config for es6
- Fix lining errors in the tests

Run linter in drone

---

src/controllers/FormTranslateController.js
src/form/FormTranslator.js
src/routes/formDataResolveRouter.js
src/services/DataContextFactory.js
src/services/PlatformDataService.js
src/utilities/axios.js
src/utilities/handlers/responseHandler.js

logger.info('Remove logging');

Remove logging

---

src/index.js
src/models/EnvironmentContext.js
src/routes/formDataResolveRouter.js
src/services/DataContextFactory.js
src/utilities/handlers/responseHandler.js
test/models/EnvironmentContext.test.js
test/services/DataDecryptor.test.js

Add private ui url token so we can use `{$.environmentContext.privateUiUrl}` to get the url of the current environment

Add private ui url token

---

README.md

Update README.md with new {$.environmentContext.privateUiUrl} token

Update README.md with new {$.environmentContext.privateUiUrl} token

---

src/services/PlatformDataService.js

Update the extendedstaffdetails endpoint to call a function rather than a table

Update the extendedstaffdetails endpoint

---

.drone.yml
README.md
env.yaml

- Use named kubenamespace variable
- Synch staging and production secrets on push to master
- Updated readme with env variable list and values
- Use protocol and log level constant variables

CB-711 Repository improvements

---

.drone.yml

Issue resolved by general performance improvements

CO-880 Remove debug level logging from translation service
